/**
 * Payment contract — interface the Order module depends on. Real implementation
 * lives in the Payments module (PayFast). The `PAYMENT_SERVICE` token resolves
 * to either `PaymentStubService` (deterministic, used by unit tests via mock)
 * or the real `PaymentsService` (bound in OrderModule via `useClass`).
 *
 * v2 contract (Phase 3 onward):
 *   - PaymentInitRequest carries the m_payment_id generated by the caller
 *     (CheckoutService creates the PaymentGroup with this ID in TX1).
 *   - PaymentInitResponse returns the signed form-flow payload as
 *     `{ actionUrl, fields }`. The frontend renders these as a hidden form
 *     and auto-submits to PayFast. Replaces the v1 `payfastRedirectUrl` shape.
 */

export interface PaymentInitRequest {
  /** One-or-many order IDs. Multi-brand checkouts pass all sibling orders in one call. */
  orderIds: string[];

  /** PayFast `m_payment_id` — caller-generated, persisted to PaymentGroup.mPaymentId. */
  mPaymentId: string;

  /** Total amount across all sibling orders, in cents (integer). */
  totalAmountInCents: number;

  buyerEmail: string;
  buyerFirstName: string;
  buyerLastName: string;

  /** Optional. SA cell number in any format; PayFast accepts a string. */
  buyerCellNumber?: string;

  /** Shown on PayFast's hosted checkout page as "what is the buyer paying for". */
  itemName: string;

  /** Optional. Longer description for the same. */
  itemDescription?: string;

  /** Optional. Frontend may override the default return URL per checkout. */
  returnUrl?: string;

  /** Optional. Frontend may override the default cancel URL per checkout. */
  cancelUrl?: string;
}

export interface PaymentInitResponse {
  /** PayFast form action URL (sandbox or production /eng/process). */
  actionUrl: string;

  /**
   * All signed fields PayFast expects, including the `signature` field.
   * Frontend renders these as hidden inputs and auto-submits the form.
   */
  fields: Record<string, string>;
}

export interface RefundRequest {
  /** PayFast UUID captured from the original payment ITN. */
  pfPaymentId: string;

  /** Refund amount in cents. May be partial; cumulative refunds enforced server-side. */
  amountInCents: number;

  /** Reason text shown to the buyer in their refund confirmation. */
  reason: string;

  /** Buyer's bank account type. PayFast requires this for refund disbursement. */
  accType: 'current' | 'savings';

  /** When true, PayFast emails the buyer about the refund. Defaults true at the API level. */
  notifyBuyer?: boolean;
}

export interface RefundResponse {
  /** PayFast's refund record identifier. */
  refundId: string;

  /** Refund processing status. PayFast confirms via a follow-up ITN. */
  status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED';

  /** Raw PayFast response payload, retained for audit on the Payment row. */
  raw: unknown;
}

export interface IPaymentService {
  initializePayment(req: PaymentInitRequest): Promise<PaymentInitResponse>;
  refundPayment(req: RefundRequest): Promise<RefundResponse>;
}

export const PAYMENT_SERVICE = 'PAYMENT_SERVICE';
