import { phpUrlencode } from './url-encode';

/**
 * Vector tests for phpUrlencode().
 *
 * Expected outputs were generated by running the same input through PHP 8.1's
 * urlencode() and locking the result here. Any divergence indicates a real
 * bug — DO NOT loosen these tests to accommodate Node-side encoder choices.
 */
describe('phpUrlencode', () => {
  describe('safe characters (PHP urlencode passes these through unchanged)', () => {
    it.each([
      ['lowercase ascii', 'abcdefghijklmnopqrstuvwxyz'],
      ['uppercase ascii', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'],
      ['digits', '0123456789'],
      ['hyphen', 'a-b-c'],
      ['underscore', 'a_b_c'],
      ['period', 'a.b.c'],
      ['safe mix', 'abc-DEF.123_xyz'],
    ])('%s → identity', (_label, input) => {
      expect(phpUrlencode(input)).toBe(input);
    });
  });

  describe('reserved characters (PHP urlencode escapes these)', () => {
    it.each([
      [' ', '+'],
      ['!', '%21'],
      ["'", '%27'],
      ['(', '%28'],
      [')', '%29'],
      ['*', '%2A'],
      ['~', '%7E'],
      ['+', '%2B'],
      ['/', '%2F'],
      ['?', '%3F'],
      ['#', '%23'],
      ['&', '%26'],
      ['=', '%3D'],
      ['%', '%25'],
      ['"', '%22'],
      ['<', '%3C'],
      ['>', '%3E'],
      ['@', '%40'],
      [':', '%3A'],
      [';', '%3B'],
      [',', '%2C'],
    ])('%s → %s', (input, expected) => {
      expect(phpUrlencode(input)).toBe(expected);
    });
  });

  describe('strings combining safe and reserved characters', () => {
    it('encodes a space-separated phrase', () => {
      expect(phpUrlencode('hello world')).toBe('hello+world');
    });

    it('encodes a URL-like value', () => {
      expect(phpUrlencode('https://yiiva.co.za/checkout/success')).toBe(
        'https%3A%2F%2Fyiiva.co.za%2Fcheckout%2Fsuccess',
      );
    });

    it('encodes ampersand and equals (signature would otherwise corrupt)', () => {
      expect(phpUrlencode('a=b&c=d')).toBe('a%3Db%26c%3Dd');
    });

    it('encodes literal plus distinctly from space', () => {
      expect(phpUrlencode('a b')).toBe('a+b');
      expect(phpUrlencode('a+b')).toBe('a%2Bb');
    });

    it('encodes percent (not double-encoded by accident)', () => {
      expect(phpUrlencode('100%')).toBe('100%25');
    });
  });

  describe('UTF-8 multi-byte sequences', () => {
    it('encodes German umlaut (Müller)', () => {
      expect(phpUrlencode('Müller')).toBe('M%C3%BCller');
    });

    it('encodes accented vowels', () => {
      expect(phpUrlencode('café')).toBe('caf%C3%A9');
    });

    it('encodes a name with apostrophe + accent', () => {
      expect(phpUrlencode("D'Évora")).toBe('D%27%C3%89vora');
    });

    it('encodes emoji (4-byte UTF-8)', () => {
      expect(phpUrlencode('🎉')).toBe('%F0%9F%8E%89');
    });
  });

  describe('edge cases', () => {
    it('returns empty string for empty input', () => {
      expect(phpUrlencode('')).toBe('');
    });

    it('does not crash on a long string', () => {
      const long = 'a'.repeat(10000);
      expect(phpUrlencode(long)).toBe(long);
    });

    it('encodes a realistic PayFast field value (item name with punctuation)', () => {
      expect(phpUrlencode("YIIVA Order #1234 (Müller's t-shirt)")).toBe(
        'YIIVA+Order+%231234+%28M%C3%BCller%27s+t-shirt%29',
      );
    });

    it('handles a typical email address', () => {
      expect(phpUrlencode('khanyi.yiiva@gmail.com')).toBe(
        'khanyi.yiiva%40gmail.com',
      );
    });
  });
});
